[server]
headless = false
port = 8502
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1A5276"
backgroundColor = "#F2F6FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1C2833"
font = "sans serif"
